# -*- coding: utf-8 -*-
"""-CodeAlpha_HangmanGame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qxibcFTSLgyYzocR18Mu39D8Hc8zAQdo
"""

import random

def hangman():
    # Step 1: Word list
    words = ["python", "shinchan", "numpy", "pandas", "script"]
    word = random.choice(words)
    guessed = ["_"] * len(word)
    attempts = 6
    used_letters = []

    print("🎯 Welcome to Hangman!")
    print("Guess the word, one letter at a time.")
    print("You have", attempts, "incorrect attempts allowed.\n")

    # Step 2: Game loop
    while attempts > 0 and "_" in guessed:
        print("Word:", " ".join(guessed))
        print("Attempts left:", attempts)
        print("Used letters:", " ".join(used_letters))
        guess = input("Enter a letter: ").lower()

        # Validate input
        if len(guess) != 1 or not guess.isalpha():
            print("❌ Please enter a single alphabet letter.\n")
            continue

        if guess in used_letters:
            print("⚠️ You already guessed that letter.\n")
            continue

        used_letters.append(guess)

        if guess in word:
            for i, letter in enumerate(word):
                if letter == guess:
                    guessed[i] = guess
            print("✅ Good guess!\n")
        else:
            attempts -= 1
            print("❌ Wrong guess!\n")

    # Step 3: Win/Loss
    if "_" not in guessed:
        print("🎉 Congratulations! You guessed the word:", word)
    else:
        print("💀 Game Over! The word was:", word)

# Run the game
if __name__ == "__main__":
    hangman()